from __future__ import annotations

from enum import StrEnum

from .errors import StateTransitionError


class RunState(StrEnum):
    CREATED = "CREATED"
    INSTALLATION_PIN_RESOLVED = "INSTALLATION_PIN_RESOLVED"
    ENVIRONMENT_PIN_RESOLVED = "ENVIRONMENT_PIN_RESOLVED"
    CAPABILITY_PREFLIGHT = "CAPABILITY_PREFLIGHT"
    BLENDER_PREFLIGHT = "BLENDER_PREFLIGHT"
    AWAITING_METHOD_PLAN = "AWAITING_METHOD_PLAN"
    METHOD_PLAN_VALIDATED = "METHOD_PLAN_VALIDATED"
    AWAITING_METHOD_SELECTION = "AWAITING_METHOD_SELECTION"
    METHOD_SELECTION_VALIDATED = "METHOD_SELECTION_VALIDATED"
    METHOD_RECONSIDERATION = "METHOD_RECONSIDERATION"
    WORKING = "WORKING"
    RENDERING_EVIDENCE = "RENDERING_EVIDENCE"
    EVIDENCE_READY = "EVIDENCE_READY"
    AWAITING_VISUAL_REVIEW = "AWAITING_VISUAL_REVIEW"
    VISUAL_REVIEW_VALIDATED = "VISUAL_REVIEW_VALIDATED"
    AWAITING_FIX_PLAN = "AWAITING_FIX_PLAN"
    FIX_PLAN_VALIDATED = "FIX_PLAN_VALIDATED"
    RENDER_QA_ACCEPTED = "RENDER_QA_ACCEPTED"
    LIVE_GUI_DECISION = "LIVE_GUI_DECISION"
    AWAITING_LIVE_GUI_REVIEW = "AWAITING_LIVE_GUI_REVIEW"
    LIVE_GUI_VALIDATED = "LIVE_GUI_VALIDATED"
    FINAL_AI_VALIDATION = "FINAL_AI_VALIDATION"
    AI_ACCEPTED = "AI_ACCEPTED"
    OWNER_REVIEW = "OWNER_REVIEW"
    HUMAN_ACCEPTED_SHA_LOCKED = "HUMAN_ACCEPTED_SHA_LOCKED"
    CURRENT_FINAL_PINNED = "CURRENT_FINAL_PINNED"
    PUBLICATION_STAGING = "PUBLICATION_STAGING"
    PUBLISHED = "PUBLISHED"
    OWNER_REVISION_REQUESTED = "OWNER_REVISION_REQUESTED"
    PUBLICATION_RETRACTED = "PUBLICATION_RETRACTED"
    NEW_GENERATION_SEEDED = "NEW_GENERATION_SEEDED"
    OWNER_REJECTED_RUN = "OWNER_REJECTED_RUN"
    OWNER_ACTION_REQUIRED = "OWNER_ACTION_REQUIRED"
    CHECKPOINTING = "CHECKPOINTING"
    CHECKPOINTED = "CHECKPOINTED"
    RESUMABLE = "RESUMABLE"


ALLOWED_TRANSITIONS: dict[RunState, set[RunState]] = {
    RunState.CREATED: {RunState.INSTALLATION_PIN_RESOLVED},
    RunState.INSTALLATION_PIN_RESOLVED: {RunState.ENVIRONMENT_PIN_RESOLVED},
    RunState.ENVIRONMENT_PIN_RESOLVED: {RunState.CAPABILITY_PREFLIGHT},
    RunState.CAPABILITY_PREFLIGHT: {RunState.BLENDER_PREFLIGHT, RunState.OWNER_ACTION_REQUIRED},
    RunState.BLENDER_PREFLIGHT: {RunState.AWAITING_METHOD_PLAN, RunState.OWNER_ACTION_REQUIRED},
    RunState.AWAITING_METHOD_PLAN: {RunState.METHOD_PLAN_VALIDATED, RunState.OWNER_ACTION_REQUIRED},
    RunState.METHOD_PLAN_VALIDATED: {RunState.AWAITING_METHOD_SELECTION},
    RunState.AWAITING_METHOD_SELECTION: {RunState.METHOD_SELECTION_VALIDATED, RunState.OWNER_ACTION_REQUIRED},
    RunState.METHOD_SELECTION_VALIDATED: {RunState.WORKING},
    RunState.METHOD_RECONSIDERATION: {RunState.AWAITING_METHOD_SELECTION},
    RunState.WORKING: {RunState.RENDERING_EVIDENCE, RunState.OWNER_ACTION_REQUIRED},
    RunState.RENDERING_EVIDENCE: {RunState.EVIDENCE_READY, RunState.OWNER_ACTION_REQUIRED},
    RunState.EVIDENCE_READY: {RunState.AWAITING_VISUAL_REVIEW},
    RunState.AWAITING_VISUAL_REVIEW: {RunState.VISUAL_REVIEW_VALIDATED, RunState.OWNER_ACTION_REQUIRED},
    RunState.VISUAL_REVIEW_VALIDATED: {
        RunState.AWAITING_FIX_PLAN,
        RunState.METHOD_RECONSIDERATION,
        RunState.RENDER_QA_ACCEPTED,
        RunState.OWNER_ACTION_REQUIRED,
    },
    RunState.AWAITING_FIX_PLAN: {RunState.FIX_PLAN_VALIDATED, RunState.OWNER_ACTION_REQUIRED},
    RunState.FIX_PLAN_VALIDATED: {RunState.WORKING, RunState.OWNER_ACTION_REQUIRED},
    RunState.RENDER_QA_ACCEPTED: {RunState.LIVE_GUI_DECISION},
    RunState.LIVE_GUI_DECISION: {
        RunState.AWAITING_LIVE_GUI_REVIEW,
        RunState.FINAL_AI_VALIDATION,
        RunState.OWNER_ACTION_REQUIRED,
    },
    RunState.AWAITING_LIVE_GUI_REVIEW: {RunState.LIVE_GUI_VALIDATED, RunState.OWNER_ACTION_REQUIRED},
    RunState.LIVE_GUI_VALIDATED: {
        RunState.WORKING,
        RunState.FINAL_AI_VALIDATION,
        RunState.OWNER_ACTION_REQUIRED,
    },
    RunState.FINAL_AI_VALIDATION: {RunState.AI_ACCEPTED, RunState.WORKING, RunState.OWNER_ACTION_REQUIRED},
    RunState.AI_ACCEPTED: {RunState.OWNER_REVIEW},
    RunState.OWNER_REVIEW: {
        RunState.HUMAN_ACCEPTED_SHA_LOCKED,
        RunState.OWNER_REVISION_REQUESTED,
        RunState.OWNER_REJECTED_RUN,
    },
    RunState.HUMAN_ACCEPTED_SHA_LOCKED: {
        RunState.CURRENT_FINAL_PINNED,
        RunState.OWNER_REVISION_REQUESTED,
    },
    RunState.CURRENT_FINAL_PINNED: {
        RunState.PUBLICATION_STAGING,
        RunState.OWNER_REVISION_REQUESTED,
    },
    RunState.PUBLICATION_STAGING: {RunState.PUBLISHED, RunState.OWNER_ACTION_REQUIRED},
    RunState.PUBLISHED: {RunState.OWNER_REVISION_REQUESTED},
    RunState.OWNER_REVISION_REQUESTED: {
        RunState.PUBLICATION_RETRACTED,
        RunState.NEW_GENERATION_SEEDED,
    },
    RunState.PUBLICATION_RETRACTED: {RunState.NEW_GENERATION_SEEDED},
    RunState.NEW_GENERATION_SEEDED: {RunState.WORKING},
    RunState.OWNER_ACTION_REQUIRED: {RunState.RESUMABLE},
    RunState.CHECKPOINTING: {RunState.CHECKPOINTED},
    RunState.CHECKPOINTED: {RunState.RESUMABLE},
}

TERMINAL_STATES = {RunState.OWNER_REJECTED_RUN}


def validate_transition(source: RunState, target: RunState, *, resume_target: RunState | None = None) -> None:
    if source in TERMINAL_STATES:
        raise StateTransitionError(f"Terminal run cannot transition: {source} -> {target}")
    if target == RunState.CHECKPOINTING and source not in {
        RunState.CHECKPOINTING,
        RunState.CHECKPOINTED,
        RunState.RESUMABLE,
        RunState.OWNER_REJECTED_RUN,
    }:
        return
    if source == RunState.RESUMABLE:
        if resume_target is None or target != resume_target:
            raise StateTransitionError(
                f"Resume transition must return to recorded state {resume_target}, got {target}"
            )
        return
    if target not in ALLOWED_TRANSITIONS.get(source, set()):
        raise StateTransitionError(f"Invalid transition: {source} -> {target}")
